import Link from "next/link";
import { Edit3, Trash2 } from "lucide-react";
import { deleteProduct } from "@/actions/admin";
import { PageHeader } from "@/components/admin/page-header";
import { Card } from "@/components/ui/card";
import { adminRows, formatINR } from "@/lib/admin/data";

type Product = { id:string; name:string; slug:string; price_paise:number; stock_quantity:number; is_active:boolean; is_featured:boolean };

export default async function AdminProductsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const rows = await adminRows<Product>("admin_products");
  const params = await searchParams;
  return <><PageHeader title="Products" description="Manage catalogue content, pricing, availability, variants, and imagery." action={<Link className="inline-flex min-h-11 items-center justify-center rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground" href="/admin/products/new">Add product</Link>} />{params.error ? <p className="mb-5 rounded-lg border border-red-900/20 bg-red-900/5 px-4 py-3 text-sm text-red-900">{params.error}</p> : null}<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[52rem] text-left text-sm"><thead className="border-b border-border bg-secondary/50 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-4">Product</th><th className="px-5 py-4">Price</th><th className="px-5 py-4">Stock</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-border">{rows.map((row) => <tr className="transition-colors hover:bg-secondary/30" key={row.id}><td className="px-5 py-5"><Link className="font-semibold text-foreground hover:text-primary focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring" href={`/admin/products/${row.id}`}>{row.name}</Link><p className="mt-1 text-xs text-muted-foreground">{row.slug}</p></td><td className="px-5 py-5 font-medium">{formatINR(row.price_paise)}</td><td className="px-5 py-5">{row.stock_quantity}</td><td className="px-5 py-5"><span className={row.is_active ? "rounded-full bg-emerald-900/10 px-2.5 py-1 text-xs font-semibold text-emerald-900" : "rounded-full bg-muted px-2.5 py-1 text-xs font-semibold text-muted-foreground"}>{row.is_active ? "Active" : "Inactive"}</span>{row.is_featured ? <span className="ml-2 text-xs text-accent-foreground">Featured</span> : null}</td><td className="px-5 py-5"><div className="flex justify-end gap-2"><Link aria-label={`Edit ${row.name}`} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-primary/25 px-3 text-sm font-semibold text-primary hover:bg-primary/5 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring" href={`/admin/products/${row.id}`}><Edit3 aria-hidden="true" size={15}/>Edit</Link><form action={deleteProduct}><input name="id" type="hidden" value={row.id}/><button aria-label={`Delete ${row.name}`} className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm font-semibold text-red-900 hover:bg-red-900/5 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring" type="submit"><Trash2 aria-hidden="true" size={15}/>Delete</button></form></div></td></tr>)}</tbody></table>{rows.length === 0 ? <p className="p-12 text-center text-sm text-muted-foreground">No products yet. Add your first product.</p> : null}</div></Card></>;
}
